name: Multi-Env Backend Deploy (Cosmos)

on:
  push:
    branches: [ dev, stage, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - env: dev
            branch: dev
            azure_credentials: AZURE_CREDENTIALS_DEV
            function_app_name: AZURE_FUNCTIONAPP_NAME_DEV

          - env: stage
            branch: stage
            azure_credentials: AZURE_CREDENTIALS_STAGE
            function_app_name: AZURE_FUNCTIONAPP_NAME_STAGE

          - env: prod
            branch: main
            azure_credentials: AZURE_CREDENTIALS_PROD
            function_app_name: AZURE_FUNCTIONAPP_NAME_PROD

    if: github.ref == format('refs/heads/{0}', matrix.branch)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Azure Functions Core Tools
      run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Install dependencies
      run: |
        cd api/visitor_counter
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets[matrix.azure_credentials] }}

    - name: Deploy to Azure Function App
      run: |
        cd api/visitor_counter
        func azure functionapp publish ${{ secrets[matrix.function_app_name] }}
