name: Multi-Env Frontend Deploy

on:
  push:
    branches: [ dev, stage, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - env: dev
            branch: dev
            storage_account_name: AZURE_STORAGE_ACCOUNT_NAME_DEV
            storage_account_key: AZURE_STORAGE_ACCOUNT_KEY_DEV

          - env: stage
            branch: stage
            storage_account_name: AZURE_STORAGE_ACCOUNT_NAME_STAGE
            storage_account_key: AZURE_STORAGE_ACCOUNT_KEY_STAGE

          - env: prod
            branch: main
            storage_account_name: AZURE_STORAGE_ACCOUNT_NAME_PROD
            storage_account_key: AZURE_STORAGE_ACCOUNT_KEY_PROD

    steps:
    - name: Check if branch matches environment
      if: github.ref == format('refs/heads/{0}', matrix.branch)
      run: 'echo "Branch matched for env: ${{ matrix.env }}"'


    - name: Checkout code
      if: github.ref == format('refs/heads/{0}', matrix.branch)
      uses: actions/checkout@v3

    - name: Upload to Azure Blob Storage
      if: github.ref == format('refs/heads/{0}', matrix.branch)
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ secrets[matrix.storage_account_name] }} \
            --destination '$web' \
            --source frontend \
            --auth-mode key \
            --account-key ${{ secrets[matrix.storage_account_key] }} \
            --overwrite


    - name: Invalidate CDN (optional)
      if: false
      run: echo "Add CDN purge step here if needed."
