name: Terraform CI/CD - Prod

# This workflow runs Terraform commands for the development environment
on:
  push:
    branches:
      - main
    paths:
      - 'infra/environments/prod/**'
      - 'modules/**'
      - 'shared/**'
#  # Trigger on pull requests to the main branch for specific paths
  pull_request:
    branches:
      - main
    paths:
      - 'infra/environments/prod/**'
      - 'modules/**'
      - 'shared/**'

jobs:
  terraform-prod:
    name: 'Terraform Plan & Apply (Prod)'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        working-directory: ./infra/environments/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="prod.tfvars" -out=tfplanprod

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplanprod


